# SPDX-License-Identifier: MPL-2.0
# This workflow is managed by gh actions-lock.
name: OSSF Scorecard

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  id-token: write
  security-events: write

jobs:
  scorecard:
    uses: hyperpolymath/standards/.github/workflows/scorecard-reusable.yml@892497fe373744874316710966b81ae6f0ea9e66
    permissions:
      contents: read
      security-events: write
      id-token: write
