# SPDX-License-Identifier: MPL-2.0
# This workflow is managed by gh actions-lock.
name: OSSF Scorecard

on:
  push:
    branches: [main, master]
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  scorecard:
    uses: hyperpolymath/standards/.github/workflows/scorecard-reusable.yml@fcb8669169b4e9f5d9848608df880ae5fae812b4
    permissions:
      contents: read
      security-events: write
      id-token: write
